### ISSUE TITLE
Middleware Pattern

### ISSUE THREAD

**Issue by notgull** [RazrFalcon/tiny-skia#101]
I'm designing an API that uses `tiny-skia` as a public dependency. So far I've designed it to just take a `PixmapMut<'_>` to render into and a specialized cache object that contains some allocations to re-use.

Other graphics APIs, like `wgpu`, have an established [middleware pattern](https://github.com/gfx-rs/wgpu/wiki/Encapsulating-Graphics-Work) that helps API users make their APIs composable with other graphics modules. Does `tiny-skia` have a model like this to ensure maximum compatibility with other packages?

If it's not just "pass along the pixmap" it should be written down somewhere.

**Comment by RazrFalcon** [comment]
>If it's not just "pass along the pixmap" it should be written down somewhere.

It is just "pass along the pixmap". The whole point of tiny-skia is to remove as much abstractions as possible. You have a pixmap and you can draw directly onto it. That's it. It's intentionally low-level.

I would describe tiny-skia as a foundation for a 2D library and not the one.

**Comment by notgull** [comment]
That makes sense, thanks!
