### ISSUE TITLE
A detailed example

### ISSUE THREAD

**Issue by rawhuul** [RazrFalcon/tiny-skia#105]
Hey there,
Please provide a detailed example of how to create a application using `tiny-skia`, I know that tiny-skia itself won’t be able to create windows and do stuff, but can you please elaborate more onto it

**Comment by notgull** [comment]
See the examples for `softbuffer`: https://github.com/rust-windowing/softbuffer/blob/master/examples/fruit.rs

**Comment by RazrFalcon** [comment]
`tiny-skia` cannot really be used to create GUI applications. It can't even draw text.
The best you and do is to create a window, get its context and draw some stuff on it. But it's hardly "an application".

**Comment by rawhuul** [comment]
thanks for your prompt response
