### ISSUE TITLE
Custom color does not take effect when rendering text with ab_glyph

### ISSUE THREAD

**Issue by hxcliff** [RazrFalcon/tiny-skia#109]
Directly using draw_pixmap might be a bit slow for me

![image](https://github.com/alexheretic/ab-glyph/assets/90960002/fe3167fd-1b45-483c-9477-faf8eb778e24)
![image](https://github.com/alexheretic/ab-glyph/assets/90960002/bd26aa84-446d-4502-ae19-01ddc31f7978)

data is pixmap.data_mut();

this is ab_glyph: [doc](https://docs.rs/ab_glyph/latest/ab_glyph/struct.OutlinedGlyph.html#method.draw)

**Comment by RazrFalcon** [comment]
Pixmap is a premultiplied RGBA. And you're modifying alpha.

**Comment by hxcliff** [comment]
> Pixmap is a premultiplied RGBA. And you're modifying alpha.

I want to get a font with a white background in the end. If I keep it unchanged, it will have a black background.

![image](https://github.com/RazrFalcon/tiny-skia/assets/90960002/2da8fddc-e090-4ba7-ac9d-a1001d4df8d3)
![image](https://github.com/RazrFalcon/tiny-skia/assets/90960002/6e6f84d3-72c6-4e7e-aed8-63a97bc28b28)

e.g.
![image](https://github.com/RazrFalcon/tiny-skia/assets/90960002/6b8f8ffa-5bcd-4fc6-b803-488e91447a33)

**Comment by RazrFalcon** [comment]
Try using `Pixmap::pixels_mut` instead. Directly modifying the internal data is a bad idea.

> If I keep it unchanged, it will have a black background.

I don't see how it is related to tiny-skia.

**Comment by hxcliff** [comment]
> Try using `Pixmap::pixels_mut` instead. Directly modifying the internal data is a bad idea.
> 
> > If I keep it unchanged, it will have a black background.
> 
> I don't see how it is related to tiny-skia.

I think I've solved it. First processing it into premultiplied RGBA and then adding a white background seems to have worked.
