### ISSUE TITLE
Any blur examples here?

### ISSUE THREAD

**Issue by mistricky** [RazrFalcon/tiny-skia#116]
I like this project and the idea behind it, I have attempt to create a picture using tiny_skia, I want to know how to draw a effect like CSS box-shadow, is there have examples or projects I can refer?

**Comment by RazrFalcon** [comment]
`tiny-skia` is very low-level library. It doesn't have filters/effects support. It's basically a tool to draw bezier paths on a bitmap.

For a simple box-blur you can use: https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/src/filter/box_blur.rs

**Comment by mistricky** [comment]
I see, thx for your reply, I'll refer this simple
