### ISSUE TITLE
SharedPixelBuffer::make_mut_bytes is quite slow

### ISSUE THREAD

**Issue by leirn** [RazrFalcon/tiny-skia#130]
I am using tiny skia to fill a Image component in slint using the example code proposed here : https://releases.slint.dev/0.2.2/docs/rust/slint/struct.image#

This call : 
```
pixel_buffer.make_mut_bytes();
```
takes around 2 secondes for a 6500 x 6500 SharedPixelBuffer.

Is there a way to speed up this operation or use another and faster implementation ?

**Comment by RazrFalcon** [comment]
There are no `make_mut_bytes` in `tiny-skia`. Are you sure it's related to it?

**Comment by leirn** [comment]
My bad, the function is in slint, I mixed the two... Sorry for the disturbance
