### ISSUE TITLE
RFC: QOI support

### ISSUE THREAD

**Issue by nishanthkarthik** [RazrFalcon/tiny-skia#140]
My motivation is to optimize the render time in this path.

```mermaid
flowchart LR
    TinySkia --> ExportPNG --> LoadPNG --> Render
```

I expect [QOI](https://qoiformat.org/) to be fast in the Export-Load cycle. WUFFS is fast for decoding pngs but it still takes ~30ms for the kind of PNGs I have. QOI is also a tiny dependency. I don't think I can avoid the filesystem in the Export-Load chain because these are two different CLI tools which export and load PNGs.

I'm also interested in contributing the changes.

Thanks!

**Comment by RazrFalcon** [comment]
You can export `Pixmap` into any format you want. Nothing is stopping you. But no other formats except for PNG will be added to `tiny-skia`.
