### ISSUE TITLE
Irregular stroke width for rounded corners

### ISSUE THREAD

**Issue by snakedye** [RazrFalcon/tiny-skia#41]
I'm observing this when I stroke a path. I used a cubic curve to draw that corner.

[Source](https://gitlab.com/snakedye/snui/-/blob/master/src/widgets/shapes/rectangle.rs#L127)
![image](https://user-images.githubusercontent.com/49378990/144482836-99b709d5-ed39-4825-8f7d-969f05faac3d.png)

**Comment by RazrFalcon** [comment]
Can you provide a minimal code example?

**Comment by snakedye** [comment]
I noticed the error was just that the border was drawn outside the buffer which made it appear clipped.

I should do minimal examples more often 😅

**Comment by RazrFalcon** [comment]
Nice! 😄
