### ISSUE TITLE
Test failed on s390x

### ISSUE THREAD

**Issue by ghost** [RazrFalcon/tiny-skia#43]
https://kojipkgs.fedoraproject.org//work/tasks/1231/82321231/build.log

---- ignore_memset stdout ----
thread 'ignore_memset' panicked at 'assertion failed: `(left == right)`
  left: `Pixmap { data: "...", width: 100, height: 100 }`,
 right: `Pixmap { data: "...", width: 100, height: 100 }`', tests/clip.rs:174:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by RazrFalcon** [comment]
This is not a supported target. Only x86 and arm64 are guarantee to work.
