### ISSUE TITLE
SIMD on AArch64 is now available on stable Rust

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/tiny-skia#46]
The README states:

> Skia also supports ARM NEON instructions, which are unavailable in a stable Rust at the moment. Therefore a fallback scalar implementation will be used instead on ARM and other non-x86 targets. So if you're targeting ARM, you better stick with Skia.

However, Rust now supports AArch64 SIMD intrinsics on stable [starting with v1.59](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html); see https://github.com/rust-lang/stdarch/pull/1266 for details.

Note that documentation still displays the intrinsics as unstable due to a rustdoc bug: https://github.com/rust-lang/stdarch/issues/1268

**Comment by CryZe** [comment]
Yeah I have an open PR for it: https://github.com/RazrFalcon/tiny-skia/pull/39

I'll try to pick it up again.

**Comment by Shnatsel** [comment]
Oh, and I see you've been working on adding it to `safe_arch` and `bytemuck` as well! Amazing! Thank you so much!

**Comment by yisibl** [comment]
@CryZe Thank you for your efforts. Looking forward to the completion of PR https://github.com/RazrFalcon/tiny-skia/pull/39.
