### ISSUE TITLE
is there a fast way to draw vertex colored triangles?

### ISSUE THREAD

**Issue by tinaun** [RazrFalcon/tiny-skia#53]
or would I have to fill each triangle 3 times for each vertex's color with a gradient pattern to get the blending correct?

**Comment by RazrFalcon** [comment]
Can you illustrate what you want?

**Comment by tinaun** [comment]
my shape data has a color associated with each point in the shape, like this classic OpenGL example: https://learnopengl.com/img/getting-started/shaders3.png

**Comment by RazrFalcon** [comment]
This is a 2D CPU library. It doesn't operate on vertexes. To draw multiple triangles like this you would need to render one to a bitmap first and then use it as a pattern.

**Comment by tinaun** [comment]
I know that, I was just wondering if there was a way I could render one without a gpu and without writing my own equivalent of SkCanvas::drawVertices - I guess someone has to.

**Comment by RazrFalcon** [comment]
I guess this is what you're looking for: 

https://github.com/google/skia/blob/1f193df9b393d50da39570dab77a0bb5d28ec8ef/src/core/SkDraw_vertices.cpp#L266

It seems like Skia uses a custom code path specifically for this function. Meaning there is no code for such a path in tiny-skia. It looks like a 500-1000 LOC patch.
I can't imagine why anyone would want anything like this and I do not plan implementing it either.
