### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by daxpedda** [RazrFalcon/tiny-skia#54]
I couldn't find any documentation on the MSRV policy. It seems that the current MSRV is set to 1.46, what does it require to push it to 1.51 to update dependencies?

**Comment by RazrFalcon** [comment]
The MSRV policy is "the older the better". I plan to bump MSRV to 1.59 when #39 would be merged.

**Comment by daxpedda** [comment]
Would it be possible to release a new version with this? Or are we waiting for #39?

**Comment by RazrFalcon** [comment]
This weekends.
