### ISSUE TITLE
BGRA8888 format

### ISSUE THREAD

**Issue by i509VCB** [RazrFalcon/tiny-skia#56]
It would be desirable to support BGRA8888 along side RGBA8888 because some windowing systems, namely Wayland are required to support what tiny-skia would call BGRA8888. Compositors can support RGBA8888 but it's optional.

**Comment by CryZe** [comment]
I've had the same problem. One thing I've considered doing is simply swapping the B and R channel for all the input colors I use for drawing.

**Comment by RazrFalcon** [comment]
You should simply swap B a R before passing to tiny-skia and swap it back after. Because the only way it could be implemented on the tiny-skia side is by doing the same before each draw call, which only be slower.

I can add a `PixmapMut` method for doing this, but that's about it.
