### ISSUE TITLE
PSA: Do not replace arrayvec with tinyvec

### ISSUE THREAD

**Issue by notgull** [RazrFalcon/tiny-skia#65]
I'll open and close this issue, if nothing else than to use as precedent if anyone else wants to do this.

I tried replacing the usage of `arrayvec` in this crate with `tinyvec`, with is an alternative with no unsafe code. However, this caused a significant degradation of performance in the benchmarks for this crate. Therefore, I don't think it is a good idea to replace `arrayvec` with `tinyvec`.

**Comment by RazrFalcon** [comment]
Thanks. I think I've tried this as well with poor results.

As for unsafe, we don't have much, except SIMD, which might be improved with #59
