### ISSUE TITLE
Add a way to recover a PathBuilder from a failed finish()

### ISSUE THREAD

**Issue by notgull** [RazrFalcon/tiny-skia#74]
Right now, [`PathBuilder::finish()`](https://docs.rs/tiny-skia/latest/tiny_skia/struct.PathBuilder.html#method.finish) returns an `Option<Path>`. However, this means that, if the function fails, the allocations used in the `PathBuilder` are lost. In the interest of preventing unnecessary allocations, it would be nice if there was some error type in `PathBuilder::finish()` that returned the cleared path.

**Comment by RazrFalcon** [comment]
This would be an extremely rare case and increasing the API complexity isn't worth it.
