### ISSUE TITLE
Feature request: `miter-clip` join style

### ISSUE THREAD

**Issue by torokati44** [RazrFalcon/tiny-skia#82]
Hi! I'm considering using this really neat project in [Ruffle](https://ruffle.rs) for drawing strokes: https://github.com/ruffle-rs/ruffle/pull/11062.

However, Flash really means "miter-clip" by the "miter" join style, so it's not a perfect match.

See:
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/GraphicsStroke.html#miterLimit
https://svgwg.org/specs/strokes/#StrokeMiterlimitProperty

Do you think it would be reasonable to add this type of join style?

**Comment by RazrFalcon** [comment]
Sure, but only if you implement it yourself.
