### ISSUE TITLE
Benchmarking site: global filter of options in additon to per-chart ones

### ISSUE THREAD

**Issue by eugenesvk** [RazrFalcon/tiny-skia#87]
Your charts have a nice feature where you can remove bars for libraries/options you don't need.
However, these are available on a per-chart basis only, so to answer the question "how much skia faster/slower than cairo" one would need to click on 4 bars per every chart

It would be great if instead you could be able to click on a global filter and then have every chart remove the unnecessary bars

**Comment by RazrFalcon** [comment]
Sadly I would not be to implement this. I'm not a web developer and the current solution is simply the easiest I was able to find.
